version: '3.9'
services:
  flask-app:
    image: flask-opencv-app:1.0
    ports:
      - "4000:80"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
    depends_on:
      - opencv-service
      - pandas-service

  opencv-service:
    image: python:3.8-slim
    command: tail -f /dev/null
    working_dir: /app
    environment:
      - OPENCV_CONTAINER=true

  pandas-service:
    image: python:3.8-slim
    command: tail -f /dev/null
    working_dir: /app
    environment:
      - PANDAS_CONTAINER=true
